### ISSUE TITLE
各種定数をConfigで調整可能にする

### ISSUE THREAD

**Issue by sitting-cat** [nucosen/Broadcast#98]
~~cli.py~~

~~clock.py~~

~~db.py~~

~~discordHandler.py~~

live.py

- [x] ユーザーエージェント
- [x] 動画タイトル
- [x] 動画説明（ただしNUCOSenへの言及が付記されるようにする）
- ~~カテゴリタグ~~
- [x] タイムシフトのON/OFF
- [x] ニコニ広告のON/OFF
- ~~ニコニコ市場の編集可否~~
- ~~引用可否~~
- ~~放送開始時刻~~

nucosen.py

- [x] お詫びメッセージ
- [x] クロージングメッセージ

personality.py

- [x] パーソナリティシステムのユーザーエージェント
- [x] ランダム放送の動画最短時間
- [x] ランダム放送の動画最長時間
- [x] 検索時のコンテクスト
- [x] ランダム放送NG動画リスト
- [x] スナップショットダウン時の休憩中動画

quote.py

- [x] 音量
- [x] メインストリームとサブストリームの別
- [x] サウンドオンリーの適用ON/OFF

sessionCookie.py

- [x] ログイン時のユーザーエージェント

全体の改修が必要

- ~~24時間放送のオンオフ（自動枠取り機能をOFFにし、1枠のみの放送が可能なようにする）~~

**Comment by komatti365** [comment]
ニコニコ市場についてですが、来月末で廃止されるので設定自体廃止したほうがいいかと思います
https://blog.nicovideo.jp/niconews/201081.html

**Comment by sitting-cat** [comment]
- `cli.py` はconfig読み込み前であるため今回は導入対象外とする
- `db.py` は #110 の汎用DB対応と同時に実施するため導入対象外とする

**Comment by sitting-cat** [comment]
- 配信カテゴリは引き続き「動画紹介」で固定とする
- 生放送の引用は引き続き不可で固定とする
- 放送開始時刻の設定は #113 で実装を検討する

**Comment by sitting-cat** [comment]
- 枠確保は #114 で検討する
